services:
    namespace:
        path: ./namespace
        reconfigure: true

        backend-configs:
            - backend/live.tfvars

        var-files:
            - tfvars/live.tfvars

    api-database:
        path: ./services/brane-api/database
        reconfigure: true

        backend-configs:
            - backend/live.tfvars

        var-files:
            - tfvars/live.tfvars

        depends-on:
            - namespace

    ferrothorn:
        path: ./services/ferrothorn
        reconfigure: true

        backend-configs:
            - backend/live.tfvars

        var-files:
            - tfvars/live.tfvars

        depends-on:
            - api-database
            - namespace

    database-enforcer:
        path: ./services/database-enforcer
        reconfigure: true

        backend-configs:
            - backend/live.tfvars

        var-files:
            - tfvars/live.tfvars

        depends-on:
            - namespace
            - api-database

    api-services:
        path: ./services/brane-api/services
        reconfigure: true

        backend-configs:
            - backend/live.tfvars

        var-files:
            - tfvars/live.tfvars

        depends-on:
            - ferrothorn
            - api-database
            - database-enforcer

    ingress:
        path: ./router/ingress
        reconfigure: true

        backend-configs:
            - backend/live.tfvars

        var-files:
            - tfvars/live.tfvars

        depends-on:
            - namespace
            - ferrothorn
            - api-services
