services:
    namespace:
        path: ./namespace

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

    ferrothorn:
        path: ./services/ferrothorn

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

        depends-on:
            - namespace

    api-database:
        path: ./services/brane-api/database

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

        depends-on:
            - namespace

    database-enforcer:
        path: ./services/database-enforcer

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

        depends-on:
            - namespace
            - api-database

    api-services:
        path: ./services/brane-api/services

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

        depends-on:
            - namespace
            - api-database
            - database-enforcer
