services:
    namespace:
        path: ./namespace

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

    service-consul:
        path: ./services/consul

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

        depends-on:
            - namespace

    service-ferrothorn:
        path: ./services/ferrothorn

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

        depends-on:
            - service-consul # TODO make it connect to consul
            - namespace
