globals:
    backend-configs:
        - backend/staging.tfvars

    var-files:
        - tfvars/staging.tfvars

services:
    state-bucket:
        path: ./s3/state-bucket
        no-destroy: true

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

    project:
        path: ./project

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars
            - tfvars/secret.tfvars

    kubernetes-cluster:
        path: ./kubernetes/cluster

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars
            - tfvars/secret.tfvars

        depends-on:
            - project

    dns-root:
        path: ./dns/root
        no-destroy: true

        backend-configs:
            - backend/live.tfvars

        var-files:
            - tfvars/live.tfvars
            - tfvars/secret.tfvars

        depends-on:
            - project

    dns-email:
        path: ./dns/email
        no-destroy: true

        backend-configs:
            - backend/live.tfvars

        var-files:
            - tfvars/live.tfvars
            - tfvars/secret.tfvars

        depends-on:
            - project
            - dns-root

# NOTE: this relies on traefik ( ../kubernetes/router/traefik ) existing
#       since it gets the ip of the load balancer that it creates
    dns-api:
        path: ./dns/api

        backend-configs:
            - backend/live.tfvars

        var-files:
            - tfvars/live.tfvars
            - tfvars/secret.tfvars

        depends-on:
            - project
            - dns-root
