services:
    network:
        path: ./fundamental/network

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

    security:
        path: ./fundamental/security

        backend-configs:
            - backend/staging.tfvars

        depends-on:
            - network

        var-files:
            - tfvars/staging.tfvars

    cluster:
        path: ./fundamental/cluster

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

        depends-on:
            - network
            - security

    service-balancer:
        path: ./service/fundamental/balancer

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

        depends-on:
            - network
            - security

    dns:
        path: ./dns
        no-destroy: true

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

        depends-on:
            - service-balancer

    service-database:
        path: ./service/fundamental/database

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

        depends-on:
            - network
            - security
            - cluster

    service-execution-role:
        path: ./service/fundamental/execution-role

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

    ecr-repos:
        path: ./ecr/repos
        no-destroy: true

        var-files:
            - tfvars/services.tfvars

    task-definitions:
        path: ./service/task-definitions
        no-destroy: true

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

        depends-on:
            - service-database
            - service-execution-role
            - ecr-repos

    services:
        path: ./service/services

        var-files:
            - tfvars/staging.tfvars

        backend-configs:
            - backend/staging.tfvars

        depends-on:
            - cluster
            - network
            - service-balancer
            - task-definitions
