services:
    network:
        path: ./fundamental/network

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars
            
    cluster:
        path: ./fundamental/cluster

        backend-configs:
            - backend/staging.tfvars

        var-files:
            - tfvars/staging.tfvars

        depends-on:
            - network
            - security

    ecr-repos:
        path: ./ecr/repos
        no-destroy: true

        var-files:
            - tfvars/services.tfvars
